package com.example.step.data.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.step.data.entity.StepEntity;

import com.example.step.data.db.greendao.StepEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stepEntityDaoConfig;

    private final StepEntityDao stepEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stepEntityDaoConfig = daoConfigMap.get(StepEntityDao.class).clone();
        stepEntityDaoConfig.initIdentityScope(type);

        stepEntityDao = new StepEntityDao(stepEntityDaoConfig, this);

        registerDao(StepEntity.class, stepEntityDao);
    }
    
    public void clear() {
        stepEntityDaoConfig.getIdentityScope().clear();
    }

    public StepEntityDao getStepEntityDao() {
        return stepEntityDao;
    }

}
