package com.example.step.data.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.step.data.entity.StepEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP_ENTITY".
*/
public class StepEntityDao extends AbstractDao<StepEntity, Long> {

    public static final String TABLENAME = "STEP_ENTITY";

    /**
     * Properties of entity StepEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CurDate = new Property(1, String.class, "CurDate", false, "CUR_DATE");
        public final static Property Steps = new Property(2, String.class, "Steps", false, "STEPS");
    };


    public StepEntityDao(DaoConfig config) {
        super(config);
    }
    
    public StepEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CUR_DATE\" TEXT," + // 1: CurDate
                "\"STEPS\" TEXT);"); // 2: Steps
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StepEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String CurDate = entity.getCurDate();
        if (CurDate != null) {
            stmt.bindString(2, CurDate);
        }
 
        String Steps = entity.getSteps();
        if (Steps != null) {
            stmt.bindString(3, Steps);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StepEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String CurDate = entity.getCurDate();
        if (CurDate != null) {
            stmt.bindString(2, CurDate);
        }
 
        String Steps = entity.getSteps();
        if (Steps != null) {
            stmt.bindString(3, Steps);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StepEntity readEntity(Cursor cursor, int offset) {
        StepEntity entity = new StepEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // CurDate
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // Steps
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StepEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurDate(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSteps(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StepEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StepEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
